### ISSUE TITLE
Fonte serif (possivelmente) não desejada

### ISSUE THREAD

**Issue by guesant** [edutucci/hawkvuemdframework#7]
No Firefox 77.0.1/Ubuntu 20.10 a fonte principal da documentação (aparenta) ser serif.
Vendo o inspetor de estilos vi que esse não era um resultado desejado. Para corrigir é só remover a aspa `"'"` da linha a seguir.

O browser está entendendo `"-apple-system,system-ui,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif"` como uma fonte só, não várias.

https://github.com/edutucci/hawkvuemdframework/blob/d1fc9ff99477c0033950fd84feef6c8d08427cc9/src/css/font.styl#L2

![Captura de tela de 2020-06-14 10-43-02](https://user-images.githubusercontent.com/43099880/84596454-e0689b00-ae2b-11ea-8b0f-43482d702e43.png)

**Comment by guesant** [comment]
Também acho que o seletor `*` para a fonte é muito forte.

Aqui os códigos de exemplo (javascript) herdam essa fonte (possivelmente) sans-serif.

Acho que um `html, body, input, button, select` estariam em um bom tamanho

**Comment by edutucci** [comment]
Eu coloquei essas fontes como padrão de cada sistema. Eu vi isso num site e to usando aqui.
Mas eu pretendo pesquisar uma fonte gratuita legal pra por no sistema.

Nao entendi isso aki:
Também acho que o seletor * para a fonte é muito forte.

**Comment by guesant** [comment]
O que eu quis dizer foi que o uso de 

```css
html, body {
  font-family: -apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif
}
```

e

```css
html, body {
            /* v note a abertura da aspa */
  font-family: '-apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif'
}
```

No primeiro caso, ele procura primeiro `-apple-system`, caso não exista no sistema, `system-ui`, `BlinkMacSystemFont` etc.
Já no segundo, ele procura `'-apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif'` como uma fonte só (como se fosse `'Arial Black'`).

Veja a diferença abrindo o developer tools e removendo as aspas da fonte principal do estilo. Se você quiser, eu posso mandar um PR.
